Repository PRJ4SW4/Borgertinget, pull requests merged in 2025-05, with the labels that each got.

#72 hotfix: Fix JWT rendering issue in frontend
  frontend/src/pages/Login.tsx
Labels: hotfix

#78 feat: Refactor Polidle Admin Endpoints and Add Quote Seeding
  backend/Controllers/Polidle/PolidleAdminController.cs
  backend/Controllers/SearchController.cs
  backend/Data/DataContext.cs
  backend/Interfaces/Repositories/IDailySelectionRepository.cs
  backend/Interfaces/Services/IDailySelectionService.cs
  backend/Migrations/20250514164514_QuoteSeeding.Designer.cs
  backend/Migrations/20250514164514_QuoteSeeding.cs
  backend/Migrations/20250514223136_InitialCreate.Designer.cs
  backend/Migrations/20250514223136_InitialCreate.cs
  backend/Migrations/DataContextModelSnapshot.cs
  backend/Persistence/Repositories/DailySelectionRepository.cs
  backend/Services/Polidle/DailySelectionService.cs
Labels: bug

#99 Added new recursive algorithm and endpoint to fix next and previous button
  backend/Services/LearningEnvironment/ILearningPageService.cs
  backend/Services/LearningEnvironment/LearningPageService.cs
Labels: hotfix

#106 Refactor PageContent: Enhance timeout management and feedback handling for question answers, so a user can retry when answering wrongly
  frontend/src/components/LearningEnvironment/PageContent.tsx
Labels: hotfix

#160 Hotfix: Logged out alert shows twice if you get on to the site with your token expired
  .config/dotnet-tools.json
  README.md
  frontend/src/App.tsx
Labels: bug, hotfix
